Handwritten digit Recognizer using MNIST Dataset.

In [17]:
import numpy as np
import pandas as pd
import tensorflow as tf 
from tensorflow import keras 
from keras.models import Sequential
from keras.layers import Dense
from keras.activations import linear, relu, sigmoid
%matplotlib inline
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('train.csv')
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
#saving the X_train and Y_train data
ans = "label"
X_train = df[df.columns.drop(ans)]
Y_train = df[[ans]].copy()
print("The X Training set:")
print(X_train)
print("\n")
print("The Y Training set:")
print(Y_train)

The X Training set:
       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0
1           0       0       0       0       0       0       0       0       0
2           0       0       0       0       0       0       0       0       0
3           0       0       0       0       0       0       0       0       0
4           0       0       0       0       0       0       0       0       0
...       ...     ...     ...     ...     ...     ...     ...     ...     ...
41995       0       0       0       0       0       0       0       0       0
41996       0       0       0       0       0       0       0       0       0
41997       0       0       0       0       0       0       0       0       0
41998       0       0       0       0       0       0       0       0       0
41999       0       0       0       0       0       0       0       0       0

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0
1           0  ...         0         0         0         0         0
2           0  ...         0         0         0         0         0
3           0  ...         0         0         0         0         0
4           0  ...         0         0         0         0         0
...       ...  ...       ...       ...       ...       ...       ...
41995       0  ...         0         0         0         0         0
41996       0  ...         0         0         0         0         0
41997       0  ...         0         0         0         0         0
41998       0  ...         0         0         0         0         0
41999       0  ...         0         0         0         0         0

       pixel779  pixel780  pixel781  pixel782  pixel783
0             0         0         0         0         0
1             0         0         0         0         0
2             0         0         0         0         0
3             0         0         0         0         0
4             0         0         0         0         0
...         ...       ...       ...       ...       ...
41995         0         0         0         0         0
41996         0         0         0         0         0
41997         0         0         0         0         0
41998         0         0         0         0         0
41999         0         0         0         0         0

[42000 rows x 784 columns]


The Y Training set:
       label
0          1
1          0
2          1
3          4
4          0
...      ...
41995      0
41996      1
41997      7
41998      6
41999      9

[42000 rows x 1 columns]

In [20]:
print("Shape of X training set: ", X_train.shape)
print("Shape of Y training set: ", Y_train.shape)

Shape of X training set:  (42000, 784)
Shape of Y training set:  (42000, 1)

In [21]:
tf.random.set_seed(1234)
model = Sequential([
    tf.keras.Input(shape=(784,)),
    Dense(units=25, activation='relu', name="layer1"),
    Dense(units=15, activation='relu', name="layer2"),
    Dense(units=10, activation='linear', name="layer3"),
  ], name = "my_model"
)

In [22]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 layer1 (Dense)              (None, 25)                19625

 layer2 (Dense)              (None, 15)                390

 layer3 (Dense)              (None, 10)                160

=================================================================
Total params: 20,175
Trainable params: 20,175
Non-trainable params: 0
_________________________________________________________________

In [23]:
[l1, l2, l3] = model.layers

In [24]:
W1, b1 = l1.get_weights()
W2, b2 = l2.get_weights()
W3, b3 = l3.get_weights()
print(f"Variable\t shape\t\t Variable\t shape\t")
print(f"W1\t\t {W1.shape}\t b1\t\t {b1.shape} \t")
print(f"W2\t\t {W2.shape}\t b2\t\t {b2.shape} \t")
print(f"W3\t\t {W3.shape}\t b3\t\t {b3.shape} \t")

Variable	 shape		 Variable	 shape
W1		 (784, 25)	 b1		 (25,)
W2		 (25, 15)	 b2		 (15,)
W3		 (15, 10)	 b3		 (10,)

In [25]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)

history = model.fit(
    X_train,Y_train,
    epochs=30
)

Epoch 1/30
1313/1313 [==============================] - 4s 2ms/step - loss: 2.3147 - accuracy: 0.4220
Epoch 2/30
1313/1313 [==============================] - 4s 3ms/step - loss: 1.1722 - accuracy: 0.5848
Epoch 3/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.8532 - accuracy: 0.7371
Epoch 4/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.6116 - accuracy: 0.8206
Epoch 5/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.4317 - accuracy: 0.8845
Epoch 6/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.3492 - accuracy: 0.9072
Epoch 7/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.2872 - accuracy: 0.9204
Epoch 8/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.2616 - accuracy: 0.9291
Epoch 9/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.2377 - accuracy: 0.9338
Epoch 10/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.2255 - accuracy: 0.9381
Epoch 11/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.2078 - accuracy: 0.9411
Epoch 12/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1896 - accuracy: 0.9475
Epoch 13/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1830 - accuracy: 0.9482
Epoch 14/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1720 - accuracy: 0.9509
Epoch 15/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1719 - accuracy: 0.9510
Epoch 16/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1627 - accuracy: 0.9541
Epoch 17/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1545 - accuracy: 0.9561
Epoch 18/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.1564 - accuracy: 0.9565
Epoch 19/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1453 - accuracy: 0.9595
Epoch 20/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.1411 - accuracy: 0.9590
Epoch 21/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1365 - accuracy: 0.9622
Epoch 22/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1347 - accuracy: 0.9609
Epoch 23/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1344 - accuracy: 0.9615
Epoch 24/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1305 - accuracy: 0.9620
Epoch 25/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.1216 - accuracy: 0.9651
Epoch 26/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1221 - accuracy: 0.9649
Epoch 27/30
1313/1313 [==============================] - 3s 2ms/step - loss: 0.1215 - accuracy: 0.9654
Epoch 28/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1179 - accuracy: 0.9645
Epoch 29/30
1313/1313 [==============================] - 4s 3ms/step - loss: 0.1169 - accuracy: 0.9656
Epoch 30/30
1313/1313 [==============================] - 3s 3ms/step - loss: 0.1122 - accuracy: 0.9675

In [26]:
X_test = pd.read_csv('test.csv')
Y_test = model.predict(X_test)
print("Shape of X_test: ", X_test.shape)
print("Shape of Y_test: ", Y_test.shape)

875/875 [==============================] - 2s 2ms/step
Shape of X_test:  (28000, 784)
Shape of Y_test:  (28000, 10)

In [27]:
print(X_test)

       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0
1           0       0       0       0       0       0       0       0       0
2           0       0       0       0       0       0       0       0       0
3           0       0       0       0       0       0       0       0       0
4           0       0       0       0       0       0       0       0       0
...       ...     ...     ...     ...     ...     ...     ...     ...     ...
27995       0       0       0       0       0       0       0       0       0
27996       0       0       0       0       0       0       0       0       0
27997       0       0       0       0       0       0       0       0       0
27998       0       0       0       0       0       0       0       0       0
27999       0       0       0       0       0       0       0       0       0

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0
1           0  ...         0         0         0         0         0
2           0  ...         0         0         0         0         0
3           0  ...         0         0         0         0         0
4           0  ...         0         0         0         0         0
...       ...  ...       ...       ...       ...       ...       ...
27995       0  ...         0         0         0         0         0
27996       0  ...         0         0         0         0         0
27997       0  ...         0         0         0         0         0
27998       0  ...         0         0         0         0         0
27999       0  ...         0         0         0         0         0

       pixel779  pixel780  pixel781  pixel782  pixel783
0             0         0         0         0         0
1             0         0         0         0         0
2             0         0         0         0         0
3             0         0         0         0         0
4             0         0         0         0         0
...         ...       ...       ...       ...       ...
27995         0         0         0         0         0
27996         0         0         0         0         0
27997         0         0         0         0         0
27998         0         0         0         0         0
27999         0         0         0         0         0

[28000 rows x 784 columns]

In [28]:
result = pd.DataFrame({'ImageId':[], 'label': []})
for i in range(0, len(Y_test)):
  id = 1+i
  label = np.argmax(Y_test[i]) 
  tmp = pd.DataFrame({'ImageId':[id], 'label': [label]})
  result = result.append(tmp, ignore_index=True)

<ipython-input-28-14d62284e4ec>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append(tmp, ignore_index=True)

In [29]:
result['ImageId'] = result['ImageId'].astype(int)
result['label'] = result['label'].astype(int)
result.to_csv('output.csv', index=False)
result.head(10)

   ImageId  label
0        1      2
1        2      0
2        3      9
3        4      4
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

In [30]:
lis = history.history['accuracy']
for i in range(len(lis)):
  print(f"accuracy {i+1}: {lis[i]}")

accuracy 1: 0.42202380299568176
accuracy 2: 0.584761917591095
accuracy 3: 0.7371428608894348
accuracy 4: 0.8205714225769043
accuracy 5: 0.8845000267028809
accuracy 6: 0.9071666598320007
accuracy 7: 0.9203571677207947
accuracy 8: 0.9291428327560425
accuracy 9: 0.9338333606719971
accuracy 10: 0.9381190538406372
accuracy 11: 0.941095232963562
accuracy 12: 0.9474762082099915
accuracy 13: 0.9482142925262451
accuracy 14: 0.9509047865867615
accuracy 15: 0.9509761929512024
accuracy 16: 0.9541190266609192
accuracy 17: 0.9561190605163574
accuracy 18: 0.9565476179122925
accuracy 19: 0.9594523906707764
accuracy 20: 0.9589999914169312
accuracy 21: 0.9621904492378235
accuracy 22: 0.9608809351921082
accuracy 23: 0.9614999890327454
accuracy 24: 0.9620237946510315
accuracy 25: 0.9651190638542175
accuracy 26: 0.96490478515625
accuracy 27: 0.9653571248054504
accuracy 28: 0.9644761681556702
accuracy 29: 0.965571403503418
accuracy 30: 0.967547595500946